networks:
  lte-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24

services:

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    networks:
      lte-network:
        ipv4_address: 172.22.0.2
    volumes:
      - mongodb_data:/data/db

  open5gs:
    image: openverso/open5gs:2.6.6
    container_name: open5gs
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      lte-network:
        ipv4_address: 172.22.0.3
    environment:
      - DB_URI=mongodb://172.22.0.2/open5gs
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
